version: "3.1"
services:
 users:
  build: ./users
  restart: always 
  links:
   - db
  ports:
   - "8080:80"
 rides:
  build: ./rides
  restart: always
  links:
   - db1
  ports:
  - "8000:80"

 db:
  image: mysql:5.7
  ports:
   - "32000:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=password

  volumes:
   - ./db:/docker-entrypoint-initdb.d/:ro
 db1:
  image: mysql:5.7
  ports:
  - "32001:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=password
  volumes:
   - ./db:/docker-entrypoint-initdb.d/:ro
